### ISSUE TITLE
Summary page uses user date

### ISSUE THREAD

**Issue by vitale82** [gwpy/gwsumm#131]
Hi Duncan,

at the LVC meeting in Glasgow I had hinted at a small date problem with the summary page.

I think what happens is that the page uses the *user* timezone to define the link of the "today" button, in the second cascade menu (the calendar).

So if someone is e.g. in Europe and try to click on "today" at 1AM local, it will get something like    

> Not Found
>
> The requested URL /~detchar/summary/day/20161117/ was not found on this server.

simply because in the US it's still the day before.

Of course, the problem becomes more and more evident as you go East in the globe.

A simple fix could be to always use LHO local time to define what "today" means.

Cheers,
salvo

**Comment by eagoetz** [comment]
I believe this has been addressed in #291
