### ISSUE TITLE
Link missing on the Tabs API instructions page

### ISSUE THREAD

**Issue by borjasor** [gwpy/gwsumm#179]
From this pages the first link is missing:
https://ldas-jobs.ligo.caltech.edu/~duncan.macleod/gwsumm/latest/tabs/websites.html#websites

More precisely: “As we have seen” which points to: https://ldas-jobs.ligo.caltech.edu/~duncan.macleod/gwsumm/latest/tabs/index

**Comment by eagoetz** [comment]
This is still broke in https://gwsumm.readthedocs.io/en/latest/tabs/websites.html; the line points to https://gwsumm.readthedocs.io/en/latest/tabs/index
