### ISSUE TITLE
NDS unexpected keyword argument

### ISSUE THREAD

**Issue by maxisi** [gwpy/gwsumm#2]
Adding the `--nds` causes a gw_summary error (I'm using your version of gw_summary, from /home/detchar/...):

```
[max.isi@ldas-pcdev3 ~]$ gw_summary day 20150115 --ifo C1 --config-file /home/max.isi/summary/config/defaults.ini -f /home/max.isi/summary/config/c1hoft.ini --multi-process 10 --nds --verbose

------------------------------------------------------------------------------
Welcome to the GW summary information system command-line interface
------------------------------------------------------------------------------

You have selected DAY mode.
Start time 2015-01-15 00:00:00.000 (1105315216.0)
End time: 2015-01-16 00:00:00.000 (1105401616.0)
Output directory: /mnt/qfs4/max.isi/day/20150115

-------------------------------------------------
Processing Seismic
States finalised
Processing 'All' state
    6 channels identified for TimeSeries
    Fetching data (from nds) for 6 channels [raw]Traceback (most recent call last):
  File "/mnt/qfs5/detchar/opt/gwpysoft/bin/gw_summary", line 731, in <module>
    segdb_error=opts.on_segdb_error)
  File "/mnt/qfs5/detchar/opt/gwpysoft/lib64/python2.6/site-packages/gwsumm/tabs/data.py", line 381, in process
    plotqueue=queue, **stateargs)
  File "/mnt/qfs5/detchar/opt/gwpysoft/lib64/python2.6/site-packages/gwsumm/tabs/data.py", line 447, in process_state
    return_=False)
  File "/mnt/qfs5/detchar/opt/gwpysoft/lib64/python2.6/site-packages/gwsumm/data.py", line 360, in get_timeseries_dict
    **ioargs)
  File "/mnt/qfs5/detchar/opt/gwpysoft/lib64/python2.6/site-packages/gwsumm/data.py", line 519, in _get_timeseries_dict
    **ioargs)
  File "/mnt/qfs5/detchar/opt/gwpysoft/lib64/python2.6/site-packages/gwpy/utils/deps.py", line 81, in wrapper
    return func(*args, **kwargs)
TypeError: fetch() got an unexpected keyword argument 'dtype'
```

Also, I thought adding an `[nds]` section in the config file was enough to make it use NDS, but it won't work unless I explicitly add the `--nds` flag as well...
Thanks,
Max

**Comment by duncanmmacleod** [comment]
Sorry for the delay, this bug is now confirmed, and I will work on a fix.

**Comment by duncanmmacleod** [comment]
This bug was hopefully resolved in gwpy/gwpy@95117b2. However, I can't get your gw_summary example to get much further due to some confusion between the channels you are passing, and the nds2 client. Please do your best to confirm that this issue is resolved, and close.

**Comment by maxisi** [comment]
Hi Duncan,

After I commenting out the tab with ambiguous channel definitions, I get
another error (an undefined variable *ftype*):

[max.isi@ldas-pcdev3 ~]$ gw_summary day 20150115 --ifo C1 --config-file
/home/max.isi/summary/config/defaults.ini -f
/home/max.isi/summary/config/c1hoft.ini --multi-process 10 --nds --verbose


------------------------------------------------------------------------------

Welcome to the GW summary information system command-line interface

------------------------------------------------------------------------------


You have selected DAY mode.

Start time 2015-01-15 00:00:00.000 (1105315216.0)

End time: 2015-01-16 00:00:00.000 (1105401616.0)

Output directory: /mnt/qfs4/max.isi/day/20150115


-------------------------------------------------

Processing PSL

States finalised

Processing 'All' state

    10 channels identified for TimeSeries

Traceback (most recent call last):

  File "/mnt/qfs5/detchar/opt/gwpysoft/bin/gw_summary", line 733, in
<module>

    segdb_error=opts.on_segdb_error)

  File
"/home/max.isi/.local/lib/python2.6/site-packages/gwsumm-0.0.0.dev617-py2.6.egg/gwsumm/tabs/data.py",
line 381, in process

    plotqueue=queue, **stateargs)

  File
"/home/max.isi/.local/lib/python2.6/site-packages/gwsumm-0.0.0.dev617-py2.6.egg/gwsumm/tabs/data.py",
line 446, in process_state

    return_=False)

  File
"/home/max.isi/.local/lib/python2.6/site-packages/gwsumm-0.0.0.dev617-py2.6.egg/gwsumm/data.py",
line 360, in get_timeseries_dict

    **ioargs)

  File
"/home/max.isi/.local/lib/python2.6/site-packages/gwsumm-0.0.0.dev617-py2.6.egg/gwsumm/data.py",
line 514, in _get_timeseries_dict

    % (source, len(qchannels), nds and ndstype or ftype))

UnboundLocalError: local variable 'ftype' referenced before assignment

Thanks,
Max

On Tue, Feb 3, 2015 at 6:51 AM, Duncan Macleod <notifications@github.com>
wrote:

> This bug was hopefully resolved in gwpy/gwpy@95117b2
> <https://github.com/gwpy/gwpy/commit/95117b2>. However, I can't get your
> gw_summary example to get much further due to some confusion between the
> channels you are passing, and the nds2 client. Please do your best to
> confirm that this issue is resolved, and close.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gwpy/gwsumm/issues/2#issuecomment-72663141>.
>



-- 
California Institute of Technology
LIGO Laboratory, MS 100-36
Pasadena, CA 91125

**Comment by duncanmmacleod** [comment]
@maxisi: I cannot reproduce the bug using an up-to-date HEAD of the master branch of gwsumm. An apparently unrelated set of commits to this repository have already fixed the bug you ran into. Please update your install of gwsumm and confirm.

**Comment by maxisi** [comment]
Fixed, thanks.
