### ISSUE TITLE
update h1guardian.ini file tab isc_lock

### ISSUE THREAD

**Issue by lauranuttall** [gwpy/gwsumm#212]
Whilst at LHO I took at look at some of the isc_lock guardian numbers and noticed they're a bit different to what is in the ini file. I've copied some relevant info below so this can be update. Thanks!

no 13
15 locking als
50 acquire_prmi
51 prmi locked
102 drmi_locked_prep_asc
201 start_tr_carm
202 carm_to_tr
203 carm_150_picometers
No 205
304 darm_to_rf
305 DHARD_WFS
306 park_als_vco
307 shutter_als
308 carm_offset_reduction
No 405,6,8
409 carm_to_refl
425 drmi_to_pop
428 engage rf violins
430 engage_asc_for_full_ifo
no 453
503 engage dc violins
504 reduce rf45 modulation depth
505 increase power
507 adjust power
520 low noise length control
550 close beam diverters
600 nominal low noise

**Comment by duncanmmacleod** [comment]
@lauranuttall, changes to the configuration files for the internal LIGO summary pages should be requested on git.ligo.org/detchar/ligo-summary-pages. As it turns out, this has already been requested [here [LIGO.ORG]](https://git.ligo.org/detchar/ligo-summary-pages/issues/81).
