### ISSUE TITLE
>1 day timescale

### ISSUE THREAD

**Issue by e-q** [gwpy/gwsumm#25]
Is there any way, or is the feature planned, to be able to look at timescales greater than one day? I.e. week, month, year, custom date ranges?

Personally, I think this could quite useful.

**Comment by duncanmmacleod** [comment]
Sorry @e-q this slipped past me. The `gw_summary --help` message outlines that there are already multiple modes supported, including 'week', 'month', and 'gps' (for arbitrary GPS intervals).

Is that what you were looking for?

**Comment by e-q** [comment]
Yes, thanks! My fault for not RTFM...
