### ISSUE TITLE
Wonder why the Virgo VT is higher than the LIGO VTs

### ISSUE THREAD

**Issue by kentaromogushi** [gwpy/gwsumm#261]
Hi Alex, 
I like the plot showing the combined VT in the summary page. But I found a point that makes me wonder why. Please correct me if I am wrong. 

The plot about VT in O2 (see https://ldas-jobs.ligo.caltech.edu/~detchar/summary/1164556817-1187733618/plots/H1L1V1-MULTI_D220F1_TIME_VOLUME-1164556817-23176801.png) shows that the Virgo VT is higher than the LIGO VT. Also, the LIGO VTs are zero all the way.

**Comment by alurban** [comment]
@kentaromogushi, that plot is a stray lying around from testing and is *not* shown on the O2 summary pages, so I should delete it. The data shown on that plot are meaningless because, at the time that plot was made, the code had a major bug which has since been fixed.

**Comment by kentaromogushi** [comment]
Thank you, Alex! I have questions about gwsumm. I will ask in slack.

**Comment by alurban** [comment]
Sounds good, thanks @kentaromogushi, I've deleted the offending files and closed this issue.
