### ISSUE TITLE
Create a new EQ mode tab

### ISSUE THREAD

**Issue by arnaudpele** [gwpy/gwsumm#316]
This ticket is a request to create a new earthquake mode (EQ mode) tab, under the LLO SEI tab with the 3 following plots : 

-[ ] 1.Ground motion plots vs IFO power vs seismon prediction
L1:ISI-GND_STS_ITMY_{X,Y,Z}_BLRMS_30M_100M -> X,Y,Z blrms  
L1:ISI-GND_STS_CS_Z_EQ_PEAK_OUTMON -> Z peak velocity
L1:LSC-POP_A_LF_OUTPUT -> Recycling power  
L1:SEI-SEISMON_LLO_R24_VELOCITY_MPS_0 (*1e9) -> Ground velocity prediction in nm/s
L1:ISI-ETMX_ST1_SENSCOR_X_FADE_CUR_CHAN_MON (*100) -> State of eq mode -100 =off, 500 = on

- [ ] 2.Guardian state SEI_CONFIG
L1:GRD-SEI_CONFIG

- [ ] 3.Guardian state SEI_EQ
L1:GRD-SEI_EQ

**Comment by duncanmmacleod** [comment]
@arnaudpele, this repo is for the software infrastructure behind the LIGO summary pages service, and does not deal with the configuration of that service (i.e. the data that are displayed). Please redirect this request to

https://git.ligo.org/detchar/ligo-summary-pages/

cc @alurban

**Comment by arnaudpele** [comment]
@duncanmmacleod, thanks. I only realized after I wrote it. Some of the summary pages, will link to this repo, others to gitlab, as mentioned in this issue https://git.ligo.org/detchar/ligo-summary-pages/-/issues/148

For my request, I opened an equivalent issue under https://git.ligo.org/detchar/ligo-summary-pages/-/issues/151
