### ISSUE TITLE
Add maintainers for readthedocs project

### ISSUE THREAD

**Issue by duncanmmacleod** [gwpy/gwsumm#342]
@eagoetz, we need to add more maintainers for the readthedocs project, currently its just me and Alex. Can each of you and @areeda, maybe also @robertbruntz [sign up](https://readthedocs.org/accounts/signup/) for developer profiles on readthedocs.org then post the usernames here and I will add you all to the project.

**Comment by robertbruntz** [comment]
robert.bruntz

**Comment by eagoetz** [comment]
@duncanmmacleod My new readthedocs account is eagoetz

**Comment by eagoetz** [comment]
@duncanmmacleod Is this done now? I don't know what are the next steps from here. Thanks
