### ISSUE TITLE
Difficult-to-understand variabiliity in update timing

### ISSUE THREAD

**Issue by Joe-Giaime** [gwpy/gwsumm#369]
I realize that O4 is still young, so please forgive me if what I describe is just launch issues...

I've found that different summary instances and different tabs show different data. It seems like some places are up to date and others are hours or even days behind.

One example 
<img width="1216" alt="Screenshot 2023-05-28 at 9 40 57 AM" src="https://github.com/gwpy/gwsumm/assets/134892314/037332b6-b7a1-4d5c-aeb6-52657152cec1"> shows LHO's segments (upper left) more-or-less up to date, but its recent range missing (lower left).

Another example 
<img width="1207" alt="Screenshot 2023-05-28 at 9 41 26 AM" src="https://github.com/gwpy/gwsumm/assets/134892314/2c54151f-2b5e-430d-bc2a-d6a755e4fd37"> is similar, with a lower graph (integrated spacetime volume) not showing LHO at all.

There are other examples, but for now I'm also testing whether this submission process works...

Cheers,
Joe Giaime, LLO.

**Comment by duncanmmacleod** [comment]
Hi @Joe-Giaime, this is better posted as a ticket on https://git.ligo.org/detchar/ligo-summary-pages/-/issues.

This project is just for the codebase that underpins the LIGO summary page instances, and doesn't configure the actual operations.
