### ISSUE TITLE
NDS `RuntimeError: Requested data were not found`

### ISSUE THREAD

**Issue by maxisi** [gwpy/gwsumm#5]
When using the `--nds` option, if data are missing `gw_summary` will return a `RuntimeError: Requested data were not found` error and crash rather than padding with zeros or producing an empty plot.

**Comment by duncanmmacleod** [comment]
@maxisi: is this still an issue?

**Comment by duncanmmacleod** [comment]
This issue hasn't seen any action in a while, will close.
