### ISSUE TITLE
VET crashing at LLO apparently due to plotting error

### ISSUE THREAD

**Issue by brennanhughey** [gwpy/gwsumm#53]
Both Marissa and I are unable to run VET at LLO due to what appears to be a matrix transpose error in the plotting code.  This includes trying to duplicate runs which worked without error several months ago.  The exact same setup runs without generating an error at LHO.  Output for run at /home/bhughey/public_html/VET/O1/hveto.a4 is below:

`bash-4.1$ ./vetcommandline.sh
WARNING: AstropyDeprecationWarning: Python 2.6 will no longer be supported from Astropy v1.2.0 and above [astropy]
/mnt/home1/detchar/opt/gwpysoft/lib64/python2.6/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

------------------------------------------------------------------------------
Welcome to the GW summary information system command-line interface
------------------------------------------------------------------------------

This is process 2505612
You have selected GPS mode.
Start time 2015-10-20 13:30:00.000 (1129383017.0)
End time: 2015-11-05 10:30:00.000 (1130754617.0)
Output directory: /mnt/home3/bhughey/public_html/VET/O1/hveto.a4/1129383017-1130754617

Loading configuration...
    Loaded 1 plugins:
        <module 'gwvet.tabs' from '/mnt/home1/detchar/opt/gwpysoft/lib64/python2.6/site-packages/gwvet/tabs.pyc'>    Loaded 0 units
    Loaded 0 channels
    Loaded 7 states
    Loaded 12 tabs [2 parents overall]
Reading trigcache from 1 files... done [1 entries]

-------------------------------------------------
Processing hveto_pad/Round 6 Pad
    Downloaded 72 segments for L1:DMT-ANALYSIS_READY:1 (99.38% coverage).
States finalised [1 total]
    Default state: 'Science'
Processing 'Science' state
    Read 2451 segments for HVT-RND6P (0.03% coverage).
    Veto evaluation results:
        Deadtime: 100.0 %
        Efficiency: 0.832947709394 %
        Efficiency/Deadtime: 0.00832947709394
        Efficiency | amplitude>=7: 0.0 %
        Efficiency/Deadtime | amplitude>=7: 0.0
        Efficiency | amplitude>=8: 0.0 %
        Efficiency/Deadtime | amplitude>=8: 0.0
        Efficiency | amplitude>=10: 0.0 %
        Efficiency/Deadtime | amplitude>=10: 0.0
        Use percentage: 0.694160881993 %
        Loudest event by snr: 0.0 %
    1 data-quality flags identified for segments
    Plotting...
/mnt/home1/detchar/opt/gwpysoft/lib64/python2.6/site-packages/matplotlib/patches.py:107: UserWarning: Setting the 'color' property will overridethe edgecolor or facecolor properties.
  warnings.warn("Setting the 'color' property will override"
        1129383017-1130754617/plots/HV-SCIENCE_4897EE_SEGMENTS-1129383017-1371600.png written
/mnt/home1/detchar/opt/gwpysoft/lib64/python2.6/site-packages/matplotlib/__init__.py:892: UserWarning: axes.color_cycle is deprecated and replaced with axes.pro
p_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
        1129383017-1130754617/plots/L1-SCIENCE_069C73_CWB_TIME_CENTRAL_FREQ_TRIGGERS-1129383017-1371600.png written
/mnt/home1/detchar/opt/gwpysoft/lib64/python2.6/site-packages/matplotlib/axes/_axes.py:5907: UserWarning: 2D hist input should be nsamples x nvariables;
 this looks transposed (shape is 1 x 2161)
  '(shape is %d x %d)' % inp.shape[::-1])
Traceback (most recent call last):
  File "/mnt/home1/detchar/opt/gwpysoft/bin/gw_summary", line 678, in <module>
    datafind_error=opts.on_datafind_error, **cache)
  File "/mnt/home1/detchar/opt/gwpysoft/lib64/python2.6/site-packages/gwsumm/tabs/data.py", line 369, in process
    **stateargs)
  File "/mnt/home1/detchar/opt/gwpysoft/lib64/python2.6/site-packages/gwvet/tabs.py", line 317, in process_state
    return super(FlagTab, self).process_state(state, *args, **kwargs)
  File "/mnt/home1/detchar/opt/gwpysoft/lib64/python2.6/site-packages/gwsumm/tabs/data.py", line 575, in process_state
    plot.process()
  File "/mnt/home1/detchar/opt/gwpysoft/lib64/python2.6/site-packages/gwsumm/plot/triggers.py", line 473, in process
    ax.hist(arr, label=label, weights=weights, **kwargs)
  File "/mnt/home1/detchar/opt/gwpysoft/lib64/python2.6/site-packages/gwpy/plotter/histogram.py", line 109, in hist
    return super(HistogramAxes, self).hist(x, **kwargs)
  File "/mnt/home1/detchar/opt/gwpysoft/lib64/python2.6/site-packages/matplotlib/__init__.py", line 1812, in inner
    return func(ax, *args, **kwargs)
  File "/mnt/home1/detchar/opt/gwpysoft/lib64/python2.6/site-packages/matplotlib/axes/_axes.py", line 5970, in hist
    raise ValueError('weights should have the same shape as x')
ValueError: weights should have the same shape as x`

**Comment by duncanmmacleod** [comment]
this bug was fixed in gwpy/gwpy#221, I just need to push an update to the gwpysoft virtualenv, I will close this issue when that has been completed.
