### ISSUE TITLE
VET consistently crashing with:  TypeError: get_triggers() got an unexpected keyword argument 'tablename'

### ISSUE THREAD

**Issue by brennanhughey** [gwpy/gwsumm#92]
My student James Pratt and I are currently unable to run VET on CIT, LHO or LLO as of July 8th, using the same setup that worked sometime earlier in the same week.

After sourcing /home/detchar/opt/gwpysoft/etc/nds2-client-user-env.sh here is output of a run at LLO:

/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

------------------------------------------------------------------------------
Welcome to the GW summary information system command-line interface
------------------------------------------------------------------------------

This is process 3007803
You have selected GPS mode.
Start time 2015-10-08 00:00:00.000 (1128297617.0)
End time: 2015-10-21 00:00:00.000 (1129420817.0)
Output directory: /mnt/home3/bhughey/public_html/VET/O1/hveto_test/1128297617-1129420817

Loading configuration...
    Loaded 1 plugins:
        <module 'gwvet.tabs' from '/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwvet/tabs.pyc'>    Loaded 0 units
    Loaded 0 channels
    Loaded 7 states
    Loaded 0 rcParams
    Loaded 6 tabs [2 parents overall]
Reading trigcache from 1 files... done [1 entries]

-------------------------------------------------
Processing hveto_pad/Round 7: PSL-PMC_MIXER_OUT_DQ Pad
    Downloaded 54 segments for L1:DMT-ANALYSIS_READY:1 (99.32% coverage).
States finalised [1 total]
    Default state: 'Science'
Processing 'Science' state
    Read 8 segments for HVT-RND7P (0.00% coverage).
Traceback (most recent call last):
  File "/home/detchar/opt/gwpysoft-2.7/bin/gw_summary", line 682, in <module>
    datafind_error=opts.on_datafind_error, **cache)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwsumm/tabs/data.py", line 370, in process
    **stateargs)
  File "/home/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/gwvet/tabs.py", line 305, in process_state
    cache=cache, tablename=self.table)
TypeError: get_triggers() got an unexpected keyword argument 'tablename'

**Comment by duncanmmacleod** [comment]
@brennanhughey, two things,

1. You should be using the `activate` script to enter the gwpysoft environment:

   ```
   . ~detchar/opt/gwpysoft/bin/activate
   ```

2. If that doesn't solve the issue, I think I just need to update the installation of VET on the LDG systems.

**Comment by brennanhughey** [comment]
Having tried the first suggestion, it appears that the installation update is also needed at CIT and LLO.  A concrete example is `/home/bhughey/public_html/VET/cWB/hveto.a4test/vetcommandline.sh` at CIT, which still generates the above error after sourcing the "activate" script.
